# Generated by Django 3.2 on 2022-01-06 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('address', models.TextField()),
                ('size', models.FloatField()),
                ('purchase_price', models.IntegerField()),
                ('estimated_profit', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('project_background', models.TextField()),
                ('applied_date', models.DateField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, '申請中'), (1, '承認'), (2, '却下')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LandReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('land', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='land.land')),
            ],
        ),
    ]
